// This file is automatically generated. Do not edit it directly.
// @ts-nocheck
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create custom supabase client with dynamic headers
const createCustomSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      debug: process.env.NODE_ENV === 'development',
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      storageKey: 'supabase.auth.token',
      onAuthStateChange: (event, session) => {
        if (process.env.NODE_ENV === 'development') {
          console.log('Supabase auth state changed:', event, session?.user?.email);
        }
      }
    },
    global: {
      headers: {
        'X-Client-Info': 'ngs-app',

      }
    }
  });
};

export const supabase = createCustomSupabaseClient();

